### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by lukebakken** [gunhak01/amqpcpp_pilot#1]
@gunhak01 - thanks for creating this repository. I will try to find time to assist you this week.

**Comment by lukebakken** [comment]
Based on [this message](https://groups.google.com/g/rabbitmq-users/c/iXHVBAbgED4) it seems like you have figured out how to use the C++ project.

**Comment by gunhak01** [comment]
I'm working with another library called akalend/amqpcpp because I don't know how to use it properly. It's a little less recognized, but it's the best I could do for now.
